test:
  domain: 'http://localhost:3000'
  pdf_generator_webhook: 'AMAZON WEBHOOK URL'
  aws_access_key_id: 'AMAZON ACCESS KEY ID'
  aws_secret_access_key: 'AMAZON SECRET ACCESS KEY'
  aws_bucket: 'AMAZON BUCKET'
  aws_region: 'AMAZON REGION'
  allow_erb_components: true
